[package]
name = "storage"
version = "0.1.0"
edition = "2021"
doctest = false

[lib]
path = "src/lib.rs"
name = "storage"
doctest = false

[dependencies]
diesel = { version = "2.0.0", features = [
  "serde_json",
  "chrono",
  "postgres",
  "r2d2",
] }
