[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "envex"
path = "src/bin/envex.rs"

[[bin]]
name = "alx"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
