[package]
edition = "2021"
name = "derive_tests"
version = "0.1.0"

[dependencies]
diesel = { version = "2.0.1", features = [
  "chrono",
  "postgres",
  "r2d2",
  "serde_json",
] }

[dev-dependencies]
async-trait = "0.1.42"
hextacy = { path = "../hextacy" }
trybuild = "1.0.80"
